### ISSUE TITLE
Cross-link whatsinstandard.com for visibility

### ISSUE THREAD

**Issue by Nightfirecat** [bdzs/whatsinstandard#1]
For ease of access, it'd be nice if each of these sites tracking Standard rotations for different games linked to each other.

Ref: glacials/whatsinstandard#23, https://github.com/glacials/whatsinstandard/pull/22#issuecomment-209221651

**Comment by bdzs** [comment]
Added the cross link

**Comment by Nightfirecat** [comment]
:+1: That takes care of this!
